### ISSUE TITLE
Feature: User can search for pokemon.

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/poke-builder#1]
## 💰 Functionality

Allow the users to search by name, type, and generation.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97194085/163871965-c4324a11-92e2-416d-9b5b-2a58ae9b6dd5.png)
![image](https://user-images.githubusercontent.com/97194085/163872022-46c6d853-8e1b-44bc-8164-f579a44b43fc.png)
![image](https://user-images.githubusercontent.com/97194085/163872049-11eb73f5-8d7c-4f39-907e-6b0ab5e5200d.png)
![image](https://user-images.githubusercontent.com/97194085/163872066-2ec4a77a-a481-41ac-ac51-5f8b8e92e8b5.png)
![image](https://user-images.githubusercontent.com/97194085/163872123-b613272c-b2e5-46cc-b9f9-d994ab12002b.png)
![image](https://user-images.githubusercontent.com/97194085/163872134-807bd494-0039-43c9-98f4-48066774dd5b.png)
![image](https://user-images.githubusercontent.com/97194085/163872149-3f199cdf-0fb9-4ce3-adab-335d70ca51d4.png)
![image](https://user-images.githubusercontent.com/97194085/163872159-75dcb7ba-b0b0-4632-a481-3a613091df38.png)

## ✅ Task List

 - [x]  Generate an html skeletons
 - [x] Make an api call to get information for the first generation
 - [x] Display all of generation 1 by default
 - [x] Add a dropdown for the search features.
   - [x] Let users search by generation
     - [x]  Dropdown with generation 1-8 as options
   - [x] Let users search by Pokémon name.
     - [x]  string as input type.
   - [x] Let users search by the Pokémon type. 
     - [x]  Dropdown with all the type as options
 - [x] make a call to ask for the information requested by the search.
 - [x] make sure that it work on both mobile and desktop
 - [x] Display the search result accordingly
