### ISSUE TITLE
Feature: User can add Pokemons to a team.

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/poke-builder#2]
## ⚙️ Functionality

> ##### Users can modify a pokemon to their liking and add it to a team or create a new team for the pokemon

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97194085/164086299-99ed6c97-7595-41c8-9d7b-c51d068e6bd7.png)
![image](https://user-images.githubusercontent.com/97194085/164086320-f1e05bb1-c8bc-46c0-b8c8-4e89bcbee6ab.png)
![image](https://user-images.githubusercontent.com/97194085/164086330-787a637b-64f5-4200-9ce0-fb68562d35c3.png)
![image](https://user-images.githubusercontent.com/97194085/164086338-f626d82c-1265-47ab-9cce-33884f1e3cbd.png)
![image](https://user-images.githubusercontent.com/97194085/164086370-162097d3-a5fe-4067-a05e-01ce8be418b8.png)
![image](https://user-images.githubusercontent.com/97194085/164086384-afd8162c-d298-40fd-ad9d-4b222d7cde2c.png)
![image](https://user-images.githubusercontent.com/97194085/164086406-db967f62-1bf8-4950-bbc1-ad9042f2a3d1.png)
![image](https://user-images.githubusercontent.com/97194085/164086424-a30a337a-0f41-45eb-aa66-e94c44d77167.png)

## ✅ Task List

 - [x] When a user clicked on a pokemon img
   - [x] take them to a form view
     - [x] Let the users decide the pokemon ability
     - [x] Item
     - [x] Nature
     - [x] and 4 moves
 - [x] Each option is a dropdown that includes all the possible choices
 - [x] When click add
   - [x] a modal will pop up
     - [x] If there is no team you can create a team
     - [x] modal show a list of all the team
       - [x] when the users click on a team add the pokemon to the team
       - [x] close the modal 
       - [x] take the users back to the pokemon display
       - [x] clear the form
 - [x] Clean up html and CSS
 - [x] fix any and all errors
