### ISSUE TITLE
Feature: User can view their teams

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/poke-builder#3]
## ⚙️ Functionality

> ##### Users can view their existing team.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97194085/164336839-5b349f89-a848-4ff5-b829-5e8129f608a4.png)
![image](https://user-images.githubusercontent.com/97194085/164336849-682c6b29-d23b-4d23-9944-93b12a907d07.png)
![image](https://user-images.githubusercontent.com/97194085/164336883-31863e3d-d2ae-4d47-b4e6-8dc580ee4657.png)
![image](https://user-images.githubusercontent.com/97194085/164336898-a86b2041-cfa5-449d-81a3-0409a8fe2147.png)

## ✅ Task List
- [x] Make a new view for the team display
- [x] Make a example html structures for the display of a team
- [x] If there are no team display "First, Create a Team"
- [x] for each team in the data
  - [x] generate a dom tree for each team
  - [x] display the name of the team
  - [x] display the sprites of the members of each team
  - [x] after saving a pokemon to any team. switch view to display the team.
- [x]  Clean up on any unnecessary css styling and html
- [x] Fix any and all bugs
