### ISSUE TITLE
Feature: User can view the detail of the teams

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/poke-builder#4]
## ⚙️ Functionality

> ##### Once the users clicked on a team, They can see the details of each pokemons.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97194085/164517385-1bf740aa-4bf2-4622-a361-ac7b32e84134.png)
![image](https://user-images.githubusercontent.com/97194085/164517399-d0401676-a26c-49e6-b5f1-f12eb68991a8.png)
![image](https://user-images.githubusercontent.com/97194085/164517409-c97ec65c-fe75-4751-a597-624aabdc2847.png)
![image](https://user-images.githubusercontent.com/97194085/164517436-f4667c20-f132-475b-a240-38280cdb8fda.png)
![image](https://user-images.githubusercontent.com/97194085/164517451-64301a6b-1a1a-4278-ae9a-11a7c497b047.png)
![image](https://user-images.githubusercontent.com/97194085/164517479-16afcb82-f1ae-434b-a723-10aecd71221c.png)

## ✅ Task List

 - [x]  when clicking on the team name banner
   - [x] open up the a a view with each team member display
     - [x]  their ability
     - [x] their moveset
     - [x] their nature
     - [x] their items
     - [x] types
  - [x]  If the team is not full (less than 6)
    - [x] have an option for the users to add a pokemon
    - [x] switch view to search
 - [x]  make it compatible on both desktop and mobile
 - [x] Clean up any unnecessary css and html
 - [x] fix any and all bugs
