### ISSUE TITLE
Feature: User can remove a pokemon from a team

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/poke-builder#5]
## ⚙️ Functionality

> ##### Users can remove a pokemon from a team.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97194085/164567998-0baeae7b-44e6-487d-9eb2-7d40047cb345.png)
![image](https://user-images.githubusercontent.com/97194085/164568008-a17ee617-c47b-4393-ba81-35fcd271dded.png)
![image](https://user-images.githubusercontent.com/97194085/164568014-e0cd32c4-a3e4-4864-a1ce-8969026cfd31.png)
![image](https://user-images.githubusercontent.com/97194085/164568031-ecc7586b-9377-406a-a527-45176677a476.png)
![image](https://user-images.githubusercontent.com/97194085/164568047-7880895c-4f93-42b3-b37b-a847b7db426b.png)
![image](https://user-images.githubusercontent.com/97194085/164568051-bfddc0ac-afe9-4113-b641-b18534836930.png)
![image](https://user-images.githubusercontent.com/97194085/164568067-eb634c1f-a759-4e8d-bdc0-2cb771d1fb91.png)
![image](https://user-images.githubusercontent.com/97194085/164568077-68661fe9-0592-4985-bdad-032a1ad581c4.png)

## ✅ Task List

 - [x] Add a trash can icon to the bottom left of the detail pokemon card
 - [x] when the user clicked on the icon
   - [x] Pop-up a modal
   - [x] Ask the users if they want to release the pokemon
   - [x] If they hit cancel close the modal
   - [x] if they hit confirm delete the pokemon from the team members list
   - [x] take them back to the team tab
 - [x] Clean up all css stylings and html skeletons
 - [x] maintain both mobile and desktop responsiveness
 - [x] fixes any and all bugs
